# Generated by Django 4.1.1 on 2022-11-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_entry_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
