# Generated by Django 4.1.1 on 2022-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='descr',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
