# Generated by Django 4.1.1 on 2022-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='descr',
            field=models.TextField(),
        ),
    ]
