# Generated by Django 4.1.1 on 2022-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_alter_topic_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
