# Generated by Django 4.1.1 on 2022-11-19 04:58

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0013_alter_entry_image_alter_entry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=0),
            preserve_default=False,
        ),
    ]
